name: dart_odbc
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  path: ^1.8.0
  ffi: ^2.0.1
  settings_yaml: ^5.0.0
  json_annotation: ^4.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  ffigen: ^7.2.6
  build_runner: ^2.3.3
  json_serializable: ^6.6.1

# dart run ffigen
ffigen:
  output: 'lib/src/generated_odbc.dart'
  headers:
    entry-points:
      - 'c_lib/dart_odbc.h'